.gitmodules, README.md, nbproject/project.properties, src/ssw/SSWConstants.java, src/ssw/filehandlers/XMLRPCClient.java, src/ssw/gui/dlgAboutBox.form, src/ssw/gui/dlgAboutBox.java, src/ssw/gui/dlgCredits.form, src/ssw/gui/dlgCredits.java
This PR merges develop into master to bring in the latest round of bugfixes and submodule updates.
=> Merge develop with bugfixes

src/ssw/gui/frmMain.form, src/ssw/gui/frmMain.java
Sister PR for sswlib drone os bug
=> Update BV calc to account for drone os

ssw/src/main/java/constants/SSWConstants.java, sswlib/src/main/java/components/Mech.java
Applies correct calculations and errata updates to LPS, null sig, and void sig, closing #23.
=> BV Calculation Fixes

sswlib/src/main/java/Print/PrintConsts.java, sswlib/src/main/java/Print/PrintMech.java, sswlib/src/main/java/Print/PrintVehicle.java, sswlib/src/main/java/Print/TWAdvGroundPoints.java, sswlib/src/main/java/Print/TWBipedPoints.java, sswlib/src/main/java/Print/TWBipedShieldedPoints.java, sswlib/src/main/java/Print/TWGroundPoints.java, sswlib/src/main/java/components/CombatVehicle.java, sswlib/src/main/java/components/Mech.java, sswlib/src/main/java/filehandlers/CVTXTWriter.java, sswlib/src/main/java/filehandlers/TXTWriter.java
* Updates TRO output for SSW and SAW
* Update Total C-Bill cost calculations
* Update output for PDF in SSW and SAW
* Add ammo cost to record sheets
Should fix #55
=> Hotfix to fix C-Bill Calculations

sswlib/src/main/java/Print/TWNavalPoints.java, sswlib/src/main/java/Print/TWQuadPoints.java, sswlib/src/main/java/Print/TWVTOLPoints.java, sswlib/src/main/java/components/CombatVehicle.java, sswlib/src/main/java/components/Mech.java
* Fix issue with VTOL / Naval / Quad causing Index out of bounds
* Fix position of Naval C-Bill text
* Fix position of VTOL C-Bill text
* Fix position of Quad C-Bill text
* Update GetTotalCost() for better code reuse
Fixes issues in #61
=> Fix comments in PR #61. Add fix for VTOL and Naval vehicles

Docs/0.7.0 Changes.txt
Forgot to ad a text file change log
=> added change log

sswlib/src/main/java/Print/PrintMech.java
Updated the printing for mechs with prototype double heat sinks. Split into two sets top set being double heat sinks and bottom being single.
=> Update printing for freezers

README.md
Fixes syntax for relative image links
=> Fix relative image links

Docs/CustomEquipment.md
This restructures and adds some new information to the Custom Equipment docs, which should hopefully clarify how the process for creating custom equipment works.
=> Update custom equipment docs

Data/Equipment/equipment.json, sswlib/src/main/java/components/CVLoadout.java, sswlib/src/main/java/components/Equipment.java
This finishes implementing the required fields for SAW to properly allocate heatsinks, as well as check whether Nuclear/Fusion engines are being used when necessary.
=> Finish implementing fields to equipment for SAW to properly allocate heatsinks

sswlib/src/main/java/components/BipedLoadout.java, sswlib/src/main/java/components/HeatSinkFactory.java, sswlib/src/main/java/components/Mech.java, sswlib/src/main/java/components/QuadLoadout.java, sswlib/src/main/java/components/TripodLoadout.java
This corrects the behavior for radical heat sinks by applying a 1.4 modifier to dissipation rather than the offensive BV.
=> Fix radical heatsink dissipation

Docs/0.7.5 Changes.txt, build.gradle
This bumps the version to 0.7.5 and adds a changelog in preparation for the next dev/nightly release.
=> Bump version and add changelog

saw/src/main/java/saw/gui/dlgAboutBox.form, saw/src/main/java/saw/gui/dlgAboutBox.java, ssw/src/main/java/ssw/gui/dlgAboutBox.form, ssw/src/main/java/ssw/gui/dlgAboutBox.java
This adds Maelwys to the credits in the "about" dialogs for SAW and SSW for his work on testing and data entry.
=> Add Maelwys to credits in about dialog

sswlib/src/main/java/Print/PrintConsts.java, sswlib/src/main/java/components/Mech.java
I fix this by just replicating what the old sort path was specifically for printing.
=> Fixes printing after the BV calculation fix

sswlib/src/main/java/components/Equipment.java
Was incorrectly doing half BV (0.5) for each crit, rather than 5% bv (0.05) for each crit.
=> Armored Equipment BV fix

Docs/0.7.5 Changes.txt, sswlib/src/main/java/Print/PrintMech.java, sswlib/src/main/java/filehandlers/Media.java
If the ssw file has an image path that does not exist we mark the image as null so that the code can try to determine the best matching image.
=> Handles Issues with SSW Image Paths

sswlib/src/main/java/Force/Unit.java, sswlib/src/main/java/filehandlers/FileCommon.java
So that the XML is valid and the names will match up with Megamek as that's the primary use of the file.
=> Convert double quotes to single quotes during MUL export

saw/src/main/java/saw/gui/dlgPrefs.form, saw/src/main/java/saw/gui/dlgPrefs.java, saw/src/main/java/saw/gui/frmVee.java
SAW Preferences are now saved to SAW specific locations and loaded from there too and used correctly.   Selected Variant clears on new Vee creation.  Lock Chassis button enables and disables based on user actions.
=> SAW GUI Fixes

sswlib/src/main/java/components/BipedLoadout.java, sswlib/src/main/java/components/QuadLoadout.java, sswlib/src/main/java/components/TripodLoadout.java
Once the other areas are filled, try to put the item in the HD.
=> Add HD to AutoAllocate

saw/src/main/java/saw/gui/frmVee.java
When the user clicks the icon on the main form it should open the dialog.
=> SAW Open Force Dialog

sswlib/src/main/java/Print/PrintVehicle.java
Code added to cover up the "(hexes)" text when Use Miniature Rules is selected.
Closes #257
=> Mini scale

saw/src/main/java/saw/gui/frmVee.java, saw/src/main/java/saw/gui/frmVeeWide.java
=> Saw fix force

sswlib/src/main/java/filehandlers/CVReader.java, sswlib/src/main/java/filehandlers/MechReader.java
Updated the Mech and CV Readers to looks for + Pulse Module and remove it from the search name then add after the equipment is found.
#235
=> Load Pulse Modules

Data/Equipment/physicals.json
to "Pile Driver" for the MM name.
#254
=> Update Heavy Duty Pile Driver

saw/src/main/java/saw/gui/dlgFiles.java, ssw/src/main/java/ssw/gui/dlgSSWFiles.java
In the open dialogs so that new users can actually find the files they need.
#205
=> Update SSW Master Url

sswlib/src/main/java/filehandlers/CVWriter.java
outside of the omni section so that we can load mixed tech correctly.
=> Output ClanCase Node

sswlib/src/main/java/filehandlers/CVReader.java
To Clan when the techbase is Clan.  Only use the node for Mixed Tech.
=> Default Case

saw/src/main/java/saw/gui/frmVee.java, saw/src/main/java/saw/gui/frmVeeWide.java, sswlib/src/main/java/components/CASE.java, sswlib/src/main/java/components/CVLoadout.java, sswlib/src/main/java/components/ifCVLoadout.java
Stop using the boolean fields and instead KNOW when the equip is in the loadout + use the item itself to tell us whether it is Clan or not.
=> Overhaul CASE code

saw/src/main/java/saw/Constants.java, saw/src/main/java/saw/Main.java, saw/src/main/java/saw/gui/dlgPrefs.java, saw/src/main/java/saw/gui/frmVee.java, saw/src/main/java/saw/gui/frmVeeWide.java
I just wanted to cleanup the layout of the GUI so tweaking things here and there to make it look better.
=> SAW UI Tune-up / Update

sswlib/src/main/java/filehandlers/CVWriter.java
The method name got changed in another branch and so this didn't show up as an issue before.
=> Fix Quirk Error on Develop

saw/src/main/java/saw/gui/frmVeeWide.java
=> Add Max C/F Summary

saw/src/main/java/saw/gui/frmVeeWide.java
Added a call to RefreshSummary() which actually resets the HeatSink spinner based on the current equipment (including insulators and capactiors).
#294
=> Update Heat Sinks on Module change

ssw/src/main/java/ssw/Main.java, ssw/src/main/java/ssw/gui/frmMain.java
Check if the new cockpit allows armor and if not remove any that might have been added.
#289
=> When cockpit changes check if it can be armored and remove if it cannot.

sswlib/src/main/java/states/stCockpitInterface.java
=> Interface Cockpit Updates

saw/src/main/java/saw/gui/frmVee.java, saw/src/main/java/saw/gui/frmVeeWide.java
Use GetNewVee in Load and Open as that appears to clear out something with turrets.
=> Fixing Turret Tonnage Loading
