- sswlib/src/main/java/components/RangedWeapon.java
Expands upon https://github.com/WEKarnesky/solarisskunkwerks/issues/13
The original patch f3819fe covered some streak SRM's, but others had slightly varied `ChatName`'s and thus were missed. `Streak` is already set to `true` for streak weapons, so `SRM` should be the only substring we need to check the name for.
This PR fixes https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/pull/25#issuecomment-513366052.
> Streak SRM: Fix errors where BV was sometimes not correctly adjusted

- sswlib/src/main/java/utilities/CostBVBreakdown.java
This PR updates the Cost BV Breakdown output to show the modifiers from Null Sigs, Void Sigs, and chameleon LPS, and to label them accordingly. Coolant pod output has also been slightly modified to make it clear exactly how much is being added, instead of a general note saying that the total includes it.
Example:
```
Offensive BV Calculation Breakdown
________________________________________________________________________________
Heat Efficiency (6 + 26 - 3 - 10 (Null-Signature System)) = 19.0
Adjusted Weapon BV Total WBV                                              297.00
-> Magshot                                                             15.00
-> Magshot                                                             15.00
-> Streak SRM-6 …
```
> Add LPS, void-sig, and null-sig to bv breakdown

- ssw/src/main/java/gui/frmMain.java
This PR should fix #27, which appears to be due to incomplete functionality in our copy of SSWLib that doesn't appear in the last official release. After calling `GetStates()`, we now check the value for null, since the last two elements will be null if the mech isn't a super heavy biped. This fixes the null pointer exception when loading the Snow Fox, although it'd be good to test other mechs as well.
> Fix crash related to super heavy biped internal structure

- saw/src/main/java/saw/gui/frmVee.java
- sswlib/src/main/java/states/stCVDisplacementSH.java
- sswlib/src/main/java/states/stCVHoverSH.java
Closes #26 by correcting the motivetype fields for SH hovercrafts and displacements. Also fixes a bug where the UI did not properly update when loading one of these vehicles.
> Fix SuperHeavy Hover and SuperHeavy Displacement MotiveType Vehicles

- ssw/src/main/java/ssw/gui/dlgPlaceableInfo.form
- ssw/src/main/java/ssw/gui/dlgPlaceableInfo.java
- ssw/src/main/java/ssw/gui/dlgWeaponInfo.form
- ssw/src/main/java/ssw/gui/dlgWeaponInfo.java
- ssw/src/main/java/ssw/gui/frmMain.form
- ssw/src/main/java/ssw/gui/frmMain.java
- sswlib/src/main/java/components/AvailableCode.java
- sswlib/src/main/java/components/CombatVehicle.java
- sswlib/src/main/java/components/Mech.java
This PR starts the process of implementing Dark Ages availability codes. IS and CL DA availability has been added to various places in the GUI such as equipment info and placeable equipment panes. The SetCodes methods have also been updated to account for both IS and CL availability codes. Currently, X is used if there is no DA data entered for the component.
Next steps are updating the 100 or so hardcoded availability codes in `sswlib/states` (in progress in the Google Docs spreadsheet), and ultimately refactoring that after the 0.7 release to use an external equipment database the way other equipment does.
> Add DA Availability Code to GUI

- sswlib/src/main/java/states/stArmorCM.java
- sswlib/src/main/java/states/stArmorHA.java
- sswlib/src/main/java/states/stArmorHD.java
- sswlib/src/main/java/states/stArmorIN.java
- sswlib/src/main/java/states/stArmorISAB.java
- sswlib/src/main/java/states/stArmorISBR.java
- sswlib/src/main/java/states/stArmorISFF.java
- sswlib/src/main/java/states/stArmorISHF.java
- sswlib/src/main/java/states/stArmorISIR.java
- sswlib/src/main/java/states/stArmorISLF.java
- sswlib/src/main/java/states/stArmorISLR.java
- sswlib/src/main/java/states/stArmorISRE.java
- sswlib/src/main/java/states/stArmorISST.java
- sswlib/src/main/java/states/stArmorISVST.java
- sswlib/src/main/java/states/stArmorMS.java
- sswlib/src/main/java/states/stArmorPatchwork.java
SSW erroneously restricted the armor type for primitive mechs to primitive armor only, while they should be able to equip all armor types. This PR adds `SetPBMAllowed(true)` to all armor types to allow primitive mechs to use them.
> Allow primitive industrialmechs to use all IS armor

- sswlib/src/main/java/filehandlers/MechReader.java
- sswlib/src/main/java/filehandlers/MechWriter.java
This PR fixes a regression that was introduced in SSWLib where the temporary placeholder omnimech loadout was not removed after it was no longer needed. This created an issue where the temporary loadout was saved when exporting a mech, which caused errors when loading it again since the temporary loadouts conflicted each other.
> Fix issue with omnimech temporary loadout when loading mechs

- saw/src/main/java/saw/gui/frmVee.java
- saw/src/main/java/saw/gui/frmVeeWide.java
Currently SAW has hardcoded values of "X/X-X-X" for a few items in the summary pane:
This PR dynamically calculates the AC for the armor and uses universal codes for the others as outlined in Interstellar Operations.
> Implement missing ACs on SAW summary pane

- ssw/src/main/java/ssw/filehandlers/HTMLWriter.java
- sswlib/src/main/java/filehandlers/TXTWriter.java
Closes #33 by exporting the booby trap in the TXT and HTML writer implementations. This causes it to appear correctly in all of the TXT export options, the "Show Text TRO Format" dialog, and the HTML export options. Let me know if there is anywhere else I missed where it still doesn't show up.
> Fix booby trap not being exported in txt/html formats

- ssw/src/main/java/ssw/gui/frmMainWide.form
- ssw/src/main/java/ssw/gui/frmMainWide.java
I forgot to update the widescreen version of SSW's main dialog with the DA availability code section in the Equipment summary pane. This PR addresses that.
> Add DA availability codes to widescreen equipment info pane

- sswlib/src/main/java/Print/PIPPrinter.java
- sswlib/src/main/java/Print/PrintMech.java
- sswlib/src/main/java/Print/TWBipedShieldedPoints.java
- sswlib/src/main/java/components/Mech.java
I have implemented a function to check for a shield on the left arm of the mech. This allows for a check to be made if the mech has any shields. I then created a new pip biped shielded class for the pip printer for when the above is true. 
This should solve issue #5
> Bugfix for armor pips incorrect with shield on biped

- sswlib/src/main/java/components/Mech.java
When applying errata for the void sig, we forgot to remove the movement modifier when void sig is being used, so a unit with a +2 movement modifier and a void sig was getting a +5 defensive modifier instead of a +3.
> Fix error with voidsig BV calculation

- BFB/build.gradle
- binconvert/build.gradle
- build.gradle
- saw/build.gradle
- ssw/build.gradle
- sswlib/build.gradle
This PR adds the `targetCompatibility` and `sourceCompatibility` directives to each project's gradle config so that any JDK >= 1.8 can compile the project and have it emit Java 8 bytecode. This means you can compile SSW on JDK 13 for instance but users with JRE8 can run the application normally.
Tested on Linux with OpenJDK 8, 11, and 13.
> Allow newer JDKs to compile Java 8 bytecode

- sswlib/src/main/java/IO/Utils.java
- sswlib/src/main/java/list/UnitList.java
This PR fixes #101 by converting Windows file path separators to Unix on Unix platforms and Unix file path separators to Windows on Windows platforms when reading the `index.ssi` cache in the SSW-Master folder.  It also adds a new IO.Utils class that we can add static helper methods to later.
Tested on Windows and Linux.
> Fix #101 - Convert Windows filepath separators to unix and vice versa

- sswlib/src/main/java/common/CommonTools.java
sswlib did not correctly handle loading from/saving to file paths containing `'`, which caused `FileNotFoundException`s when it encountered them. Now, instead of simply stripping them out, SSW URL encodes them like it does for other special characters.
> Escape single quotes in file paths to handle paths containing them

- BFB/src/main/java/BFB/GUI/frmBase.form
- BFB/src/main/java/BFB/GUI/frmBase.java
Two menu items without any implemented backend functionality were found under the "View" menu in BFB: A "Select Unit List" entry that was not referenced anywhere else in the code, and a "jMenuItem8" that appears to have been added erroneously using the Netbeans form builder with boilerplate initialization code. 
Select Unit List could have logic implemented elsewhere that never got wired to the menu item so this P just hides it for now. jMenuItem8 has been removed from the menu completely.
> Cleanup view menu

- ssw/src/main/java/ssw/gui/frmMain.java
The "Load Force Balancer" menu item under Tools in SSW uses a hardcoded filename for the BFB jar, which breaks on case-sensitive filesystems like Linux. This commit correctly capitalizes the filename but also checks for the lowercase version when it's not found. If it still can't find the jar, it prints an error dialog saying it couldn't find "BFB.jar".
> SSW: Handle BFB jar name on case-sensitive filesystems

- saw/src/main/java/saw/gui/frmVee.form
- saw/src/main/java/saw/gui/frmVee.java
- saw/src/main/java/saw/gui/frmVeeWide.form
- saw/src/main/java/saw/gui/frmVeeWide.java
- sswlib/src/main/java/Print/PrintConsts.java
- sswlib/src/main/java/components/CVArmor.java
- sswlib/src/main/java/components/CVLoadout.java
- sswlib/src/main/java/components/CombatVehicle.java
- sswlib/src/main/java/components/LocationIndex.java
- sswlib/src/main/java/components/SponsonTurret.java
- sswlib/src/main/java/components/ifCVLoadout.java
- sswlib/src/main/java/filehandlers/CVReader.java
- sswlib/src/main/java/filehandlers/CVTXTWriter.java
- sswlib/src/main/java/filehandlers/FileCommon.java
- sswlib/src/main/java/utilities/CVCostBVBreakdown.java
This PR implements sponson turrets in SAW and sswlib. They were only superficially added before--they were being treated as a regular turret and didn't really follow any of the rules for sponsons. 
Tested by myself, CampaignAnon, and Maelwys (thanks guys!) and is believed to be working to the best of our knowledge. Closes #39
> SAW/sswlib: Implement Sponson Turrets

- sswlib/src/main/java/components/CombatVehicle.java
GetDryCost() was not factoring in Sponson Turret costs when calculating the cost of a unit. This PR simply adds the final c-bill cost of the sponson to the calculation.
> Account for Sponson Turret Cost in GetDryCost

- sswlib/src/main/java/components/Engine.java
- sswlib/src/main/java/states/ifEngine.java
- sswlib/src/main/java/states/stEngineCLXL.java
- sswlib/src/main/java/states/stEngineCLXXL.java
- sswlib/src/main/java/states/stEngineFission.java
- sswlib/src/main/java/states/stEngineFuelCell.java
- sswlib/src/main/java/states/stEngineFusion.java
- sswlib/src/main/java/states/stEngineICE.java
- sswlib/src/main/java/states/stEngineISCF.java
- sswlib/src/main/java/states/stEngineISLF.java
- sswlib/src/main/java/states/stEngineISXL.java
- sswlib/src/main/java/states/stEngineISXXL.java
- sswlib/src/main/java/states/stEngineNone.java
- sswlib/src/main/java/states/stEnginePrimitiveFission.java
- sswlib/src/main/java/states/stEnginePrimitiveFuelCell.java
- sswlib/src/main/java/states/stEnginePrimitiveFusion.java
- sswlib/src/main/java/states/stEnginePrimitiveICE.java
Closes #94. Previously, sswlib was only accounting for shielding weight on fusion engines, although it should have been doing this for fission engines as well. This required adding an `IsFission()` method on the engine states and interface, which returns false for everything except the two fission engine types.
> sswlib: Fission engine shielding weight

- sswlib/src/main/java/Force/Unit.java
This commit fixes an issue with resolving base directories in BFB's print units dialog when SSW hasn't been ran first to populate the preferences. Currently, only SSW's preferences file is read, and if SSW has never been ran, it will return an empty string for the SSW master list directory path. This causes an error when loading the unit that causes record sheets not to be loaded when printing a force.
This is a quick fix by having it fall back to the BFB prefs file if it can't load the correct keys from the SSW prefs file. 
Closes #54
> fall back to BFB prefs if SSW prefs are missing

- sswlib/src/main/java/Print/PrintMech.java
The print preview dialog was previously ignoring the image specified by the user after clicking "Choose TRO Pic", and instead was only loading the image saved in the Fluff tab of SSW. This change addresses that by first checking to see if a user explicitly chose a TRO pic in the print preview screen before falling back to the fluff image.
Fixes #42
> Stop ignoring "Choose TRO Pic" image in print preview

- saw/src/main/java/saw/gui/frmVee.java
- saw/src/main/java/saw/gui/frmVeeWide.java
Closes #59 
When loading/opening vehicles, the turret selection menu was not refreshed based on whether the vee had a single, dual, or no turret, and instead just used whatever value it was previously set to. This commit simply checks the turret status of the vee before setting the menu item.
> Correctly set turret selector when loading CVs

- .github/workflows/ci.yml
This adds a basic GitHub Action for CI of SSW and its associated programs. [Over at MM we've expanded our usage to include other actions](https://github.com/MegaMek/megamek/tree/master/.github/workflows) (nightlies across multiple OS, updating Maven repo) too, but this one gets your foot in the door and would add CI capabilities to any pull requests.
> Add basic GitHub Action for CI

- sswlib/src/main/java/components/RangedWeapon.java
@WEKarnesky ping me if this is incorrect, but my understanding of #138 was that Streak LRMs and iATMs should be treated exactly like streak SRMs when calculating heat for offensive BV. We adjusted it for Streak SRMs [in this PR](https://github.com/WEKarnesky/sswlib/pull/8) but it looks like we needed to apply it to iATMs and LRMs as well, which this PR addresses.
> Fix #138 - reduce heat multiplier on SLRMs and iATMs

- sswlib/src/main/java/components/CVArmor.java
- sswlib/src/main/java/components/LocationIndex.java
Fixes #156 by removing sponson turrets from the Armor locations array defined in CVArmor.java. Per Maelwys, Sponson Turrets can't be armored, but they still needed to be referenced as a location to be able to equip items to them.
Note that this required moving the sponsons to the end of the Locations list in LocationIndex.java because each integer is used to index into the armor location array.
> Remove sponsons from armor locations

- Data/Equipment/equipment.json
- Data/Equipment/physicals.json
- sswlib/src/main/java/components/BipedLoadout.java
- sswlib/src/main/java/components/CVLoadout.java
- sswlib/src/main/java/components/QuadLoadout.java
- sswlib/src/main/java/components/TripodLoadout.java
- sswlib/src/main/java/components/abPlaceable.java
- sswlib/src/main/java/filehandlers/JsonReader.java
- sswlib/src/main/java/filehandlers/JsonWriter.java
I'd previously left out equipment exclusions and physical weapon mech modifiers when converting the equipment files from binary to JSON. This PR updates the JSON models to serialize and deserialize the relevant fields to populate these objects, as well as instructing gson not to serialize null values going forward. This means we won't need to update all the models when adding new fields.
While I was at it, I also looked at #107 and determined the root cause was `CheckExclusions()` was using `.contains()` rather than `.equals()` when comparing the item name to the exclusions, so if the exclusion was a substring of the item being checked, it would conflict and throw an exception. I changed all of these calls to `.contains()` because I can't think of a logical reason to use the substring. …
> Serialize exclusions and mechmodifiers in equipment JSON; fix some exclusion errors

- sswlib/src/main/java/components/CVArmor.java
- sswlib/src/main/java/components/CombatVehicle.java
- sswlib/src/main/java/states/ifCombatVehicle.java
- sswlib/src/main/java/states/stCVDisplacement.java
- sswlib/src/main/java/states/stCVDisplacementSH.java
- sswlib/src/main/java/states/stCVHover.java
- sswlib/src/main/java/states/stCVHoverSH.java
- sswlib/src/main/java/states/stCVHydrofoil.java
- sswlib/src/main/java/states/stCVSubmarine.java
- sswlib/src/main/java/states/stCVTracked.java
- sswlib/src/main/java/states/stCVVTOL.java
- sswlib/src/main/java/states/stCVWheeled.java
- sswlib/src/main/java/states/stCVWiGE.java
This addresses #130 by adding the +1 TMM to WiGE's and adding an additional modifier to fix an error in the defensive BV calculation for combat vehicles. The IsVTOL and IsWIGE methods were refactored to default to false so that they don't have to be explicitly implemented in every class that uses the combat vehicle interface.
> Fix SAW BV Issues

- sswlib/src/main/java/components/Equipment.java
This starts to address #163 by adding some fields SAW needs to properly calculate the number of heatsinks when adding equipment. We will still need to add some logic to SAW to use this information, as well as update the equipment JSON where appropriate.
> Add fields to equipment for saw to calculate heatsinks properly

- BFB/src/main/java/BFB/Common/Constants.java
- Docs/0.7.4.1 Changes.txt
- build.gradle
- saw/src/main/java/saw/Constants.java
- ssw/src/main/java/ssw/constants/SSWConstants.java
- ssw/src/main/java/ssw/gui/frmMain.java
- ssw/src/main/java/ssw/gui/frmMainWide.java
- sswlib/src/main/java/common/Constants.java
- sswlib/src/main/java/components/BipedLoadout.java
- sswlib/src/main/java/components/Mech.java
- sswlib/src/main/java/components/QuadLoadout.java
- sswlib/src/main/java/components/TripodLoadout.java
- sswlib/src/main/java/components/ifMechLoadout.java
7.4 contained a regression caused by refactoring the `CheckExclusions()` logic to fix a different bug with HarJels conflicting with themselves. Previously, `CheckExclusions()` only checked if equipped items contained a substring, rather than comparing the whole name. `HasECM()`, `HasProbe()`, and `HasC3()` relied on this behavior to act as a wildcard search for equipped items, causing them to not be found when the behavior changed, causing #167.
This hotfix corrects the issue by refactoring the `Has` functions to use their own conditions to conduct the search, keeping `CheckExclusions` working by matching only the exact name. Mech Loadouts now expose a new method that returns a single `List` of all equipped items, allowing callers to easily search the whole mech for equipment rather than …
> Fix ECM/Probe/C3 Requirements

- BFB/build.gradle
- BFB/src/main/java/BFB/Common/Constants.java
- build.gradle
- saw/build.gradle
- saw/src/main/java/saw/Constants.java
- saw/src/main/java/saw/Main.java
- saw/src/main/java/saw/gui/dlgAboutBox.java
- saw/src/main/java/saw/gui/frmVee.java
- saw/src/main/java/saw/gui/frmVeeWide.java
- ssw/build.gradle
- ssw/src/main/java/ssw/constants/SSWConstants.java
- ssw/src/main/java/ssw/gui/dlgAboutBox.java
- ssw/src/main/java/ssw/gui/frmMain.java
- ssw/src/main/java/ssw/gui/frmMainWide.java
- sswlib/src/main/java/common/Constants.java
This cleans up our gradle build system substantially by removing unneeded code, comments, and correcting the task order so that the `releaseBuild` task actually runs how it's supposed to. 
We now only have to update the version number and release type in a single place (the root `build.gradle`), and the build system will generate a `build.properties` file for each project during compilation and include them as a resource to be read from the Java. The date is resolved dynamically, and is appended to the archive name and version info in the apps when it's set to "Nightly". The properties files are written to directories under each project's `build/` rather than `src/main/resources`, so they will be automatically cleaned up when gradle `clean` tasks are ran.
Each app has had new methods …
> Build system improvements

- BFB/build.gradle
- binconvert/build.gradle
- saw/build.gradle
- ssw/build.gradle
This dynamically populates the classpath when executing the jar task, so all dependencies will automatically be added rather than us having to remember to hardcode them when new libs are added.
> Dynamically resolve classpath in jar tasks

- build.gradle
- sswlib/build.gradle
- sswlib/src/main/java/filehandlers/MechReader.java
- sswlib/src/main/java/filehandlers/UnitCacheParser.java
- sswlib/src/main/java/list/UnitList.java
- sswlib/src/main/java/list/UnitListData.java
- sswlib/src/main/java/list/ifUnitData.java
The SSW-Master `index.ssi` file was being parsed manually, with a simple `String.split(",")` to separate the fields. This led to some issues like commas in certain fields breaking the file. I looked at both JSON and raw objects via Kryo as alternative formats for storing the unit cache, but JSON would bloat the file to 2-3x the current size and Kryo added a few hundred extra lines of code due to the need to write custom serializers, and I wanted to avoid introducing that complexity.
This is more of a drop-in replacement for what we were doing before. The Commons CSV library properly quotes records when needed and is able to pass the appropriate fields back to the classes being deserialized, so they can use more or less the same constructors they were using before.
This also fixes a bug in …
> Use csv library to read and write unit list cache

- sswlib/src/main/java/components/CVLoadout.java
https://bg.battletech.com/forums/techmanual/answered-ammunition-slots-on-combat-vehicles/
There was a rules call reversal on how to allocate space for ammo bins on combat vehicles. Turns out, all ammo types for a class of weapon (for example, MML-3) count as a single bin. This PR fixes adjusts for that by creating a set of unique AmmoIndexes (which identify the corresponding weapon type) and then returning the length of the set.
> Correct saw ammo bin space calculations after call reversal

- .github/workflows/ci.yml
This uses the `upload-artifact-as-is` Github action to upload a properly named/versioned release zip on CI actions. I've also updated the action to build on every push/PR to develop as well as master to facilitate testing bugfixes/features (no more manually compiling and uploading binaries to PR/issue threads to link in Discord).
> Upload release zip artifact on Pushes/PRs to develop and master

- sswlib/src/main/java/components/Mech.java
This correctly applies the -15 BV per crit slot for extended fuel tanks described in #158. Note the negated `if (Explosive)` check at the bottom; I felt like this might be better than changing the `IsExplosive()` value in `ExtendedFuelTank.java` since that could lead to confusion later ("Why aren't fuel tanks marked explosive? Is that a bug?").
I've spot checked a few mechs with this item equipped and the new BVs agree with the MUL, but I'm going to give Maelwys and others a chance to test before I mark this ready for review.
> Fix explosive BV calculation for extended fuel tanks

- sswlib/src/main/java/components/PartialWing.java
Partial Wings seem to have been affected by an off-by-one error when checking the available critical slots on the torsos, resulting in a failure to load the Ostscout IIC, which had exactly enough critical slots left on the right torso. 
After this fix all mechs appear to have loaded successfully using the magic wand from the "Open" dialog.
> Fix off by one error when equipping partial wing

- saw/src/main/java/saw/gui/frmVee.java
- saw/src/main/java/saw/gui/frmVeeWide.java
Fix #160 by clearing the checkboxes in the chassis selector and appropriately re-selecting them when repainting it. Note there still appear to be some bugs around `FlushIllegal` - i.e., you can select limited amphibious and then switch to a hovercraft, and the box is disabled but stays checked.
> Refresh checkboxes when refreshing the SAW chassis selector

- .github/workflows/ci.yml
This will trigger build actions when PRs get merged into develop so that Maelwys and other testers can have comprehensive dev snapshots instead of just individual bugfix/feature branches.
> Trigger builds on pushes to develop

- sswlib/src/main/java/components/BipedLoadout.java
- sswlib/src/main/java/components/QuadLoadout.java
- sswlib/src/main/java/components/TripodLoadout.java
- sswlib/src/main/java/components/ifMechLoadout.java
This adds a `HasItem(String lookupName)` to the various mech loadouts to check if a piece of equipment is equipped anywhere on the mech. The other versions currently require an actual instance of `abPlaceable`, which is harder to create from other parts of the code.
> Add function to check if a mech has an item equipped by name

- Data/Equipment/equipment.json
- sswlib/src/main/java/components/CVPowerAmplifier.java
- sswlib/src/main/java/components/PowerAmplifier.java
This updates SSW and SAW to correctly handle power amps in Equipment, when it previously only considered them for weapons. It also fixes a bug where fractional accounting on power amps was being multipled by the wrong coefficient, resulting in tonnage values that were 2x the correct value.
This is a work in progress until we have a chance to update and test other fields.
> Poweramps and Fractional Accounting

- sswlib/src/main/java/utilities/CostBVBreakdown.java
Apparently `0.2f` rounds to 3, which led to a rounding error when displaying the coolant pod bonus in the cost/bv breakdown pane.
> Fix rounding error when determing coolant pod bonuses in bv breakdown

- sswlib/src/main/java/components/BipedLoadout.java
- sswlib/src/main/java/components/QuadLoadout.java
- sswlib/src/main/java/components/TripodLoadout.java
`RequiresNuclear` and `RequiresFusion` were added to equipment.json as they were needed for some exclusions and heatsink calculations. The logic in SAW has already been updated to check for these, but I forgot to update SSW as well.
> Check for requiresnuclear and requiresfusion on equipment

- sswlib/build.gradle
This adds a gradle plugin to allow publishing sswlib to a local maven repository. To run it, you can use your IDE or run `./gradlew run sswlib:publish` from the command line, which will compile sswlib and push it to a local repository on your machine (`~/.m2` on Linux). Once published, if you want to use sswlib in another project, you simply add the following to your new project's `build.gradle`:
```
repositories {
mavenCentral()
mavenLocal()
}
dependencies {
compile 'com.solarisskunkwerks:sswlib:0.7.5'
}
```
This will pull sswlib and all of it's dependencies from your local repo (or maven central if they arent published locally) and automatically add them to your build.
Future work could involve publishing sswlib to Maven Central so that anyone can pull it without publishing it locally …
> Add task to publish sswlib to local maven repo

- BFB/build.gradle
- BFB/src/main/java/BFB/Common/Constants.java
- build.gradle
- saw/build.gradle
- saw/src/main/java/saw/Constants.java
- saw/src/main/java/saw/gui/dlgAboutBox.java
- ssw/build.gradle
- ssw/src/main/java/ssw/constants/SSWConstants.java
- ssw/src/main/java/ssw/gui/dlgAboutBox.java
This changes the build system to use semver release types instead of `Nightly` + `date()` for pre-release versions. Under this system, the major version (`version` in `build.gradle`) will be bumped to the next release after each stable, so it will be 0.7.5 in the develop branch until 0.7.5 stable is released, at which point it will be bumped to 0.7.6. The `release` variable under it will be set to `SNAPSHOT` until a new dev alpha/beta release is ready, at which point it will be changed to `Alpha`/`Beta` <number>. So the first 0.7.5 dev release would be as follows:
```
version '0.7.5'
ext {
release='Alpha 1'
}
```
The `zipRelease` task appends the release type to the zip file name when it's anything other than stable.
> Change release types from nightly to alpha/beta/rc

- Data/Equipment/physicals.json
- sswlib/src/main/java/components/Mech.java
This changes how weapons are sorted for BV purposes.  Originally it was sorted by BV only (highest first) now it sorts by BV (highest first), then by heat (lowest first) when BV is equal.
> Sort weapons by BV (highest first) then heat (lowest first)

- sswlib/src/main/java/components/Mech.java
If the mech is an instance of a Quad, then the LA and RA are actually legs and we shouldn't look to the Torso for the ammo explosion penalty.
> Quad Leg Ammo BV fix

- saw/src/main/java/saw/gui/frmVee.java
- saw/src/main/java/saw/gui/frmVeeWide.java
- ssw/src/main/java/ssw/gui/frmMain.java
- ssw/src/main/java/ssw/gui/frmMainWide.java
- sswlib/src/main/java/components/CVArmor.java
- sswlib/src/main/java/components/MechArmor.java
- sswlib/src/main/java/states/ifArmor.java
- sswlib/src/main/java/states/stArmorCLFF.java
- sswlib/src/main/java/states/stArmorCLFL.java
- sswlib/src/main/java/states/stArmorCLLR.java
- sswlib/src/main/java/states/stArmorCLRE.java
- sswlib/src/main/java/states/stArmorCM.java
- sswlib/src/main/java/states/stArmorHA.java
- sswlib/src/main/java/states/stArmorHD.java
- sswlib/src/main/java/states/stArmorIN.java
- sswlib/src/main/java/states/stArmorISAB.java
- sswlib/src/main/java/states/stArmorISBR.java
- sswlib/src/main/java/states/stArmorISFF.java
- sswlib/src/main/java/states/stArmorISHF.java
- sswlib/src/main/java/states/stArmorISIR.java
- sswlib/src/main/java/states/stArmorISLF.java
- sswlib/src/main/java/states/stArmorISLR.java
- sswlib/src/main/java/states/stArmorISRE.java
- sswlib/src/main/java/states/stArmorISST.java
- sswlib/src/main/java/states/stArmorISVST.java
- sswlib/src/main/java/states/stArmorMS.java
- sswlib/src/main/java/states/stArmorPBM.java
- sswlib/src/main/java/states/stArmorPatchwork.java
Armor now has an AllowOmni value, currently only Hardened prevents it. As armor is fixed when locking the Omni chassis, we check the armor at that time.
> Prevent making an Omnimech with Hardened Armor

- .github/workflows/ci.yml
- BFB/build.gradle
- BFB/src/main/java/BFB/Common/Constants.java
- build.gradle
- saw/build.gradle
- saw/src/main/java/saw/Constants.java
- ssw/build.gradle
- ssw/src/main/java/ssw/constants/SSWConstants.java
This updates the gradle build system and Github CI to append the commit hash to version numbers both in the program and in the release archives. The hash will be displayed in the titlebar and about dialog in any **non-Stable** release. Therefore, I recommend changing the `release` variable in the root build.gradle to `RC` going forward and only using `Stable` for full stable releases.
Github CI will append the hash in all actions because there isn't a good way to resolve the release type from there. I figure that won't be a problem since tagged stable release binaries will still probably be uploaded manually.
> Add commit hash to non-Stable builds

- ssw/src/main/java/ssw/gui/dlgArmorTonnage.java
Just a 2 line change to enhance quality of life.
When I was farting around SSW a few days ago I like messing around with armor tonnage/weapon loadouts, it made no sense to me why the "Set Armor Tonnage" didn't default its text box to the current tonnage but it DOES show the max tonnage. Turns out it's super easy to do.
Before (with a Trebuchet TBT-9K):
After:
> QoL: 'Set Armor Tonnage' now is pre-filled with current tonnage

- ssw/src/main/java/ssw/gui/frmMain.java
- ssw/src/main/java/ssw/gui/frmMainWide.java
This fixes #222 by assigning a valid reference to the Mech's quirk list in the view without loading it into the program first. The dialog's quirk list model was only being set by `LoadMechIntoGUI()`, but this method isn't called when designing a new mech, so the new Mech's table never got updated when new quirks were added.
> Fix issue saving quirks on new mechs

- sswlib/src/main/java/filehandlers/JsonReader.java
This fixes #226 by setting `CurLotSize` to `LotSize`, which represents the maximum lot size for most ammunition. This bug occurred because in the old method, the `Ammunition` constructor explicitly set CurLotSize to LotSize when loading objects, which the default Gson deserializer doesn't do. 
IMO it's not ideal to iterate over the ammo list in the JsonReader class after loading it, but the only other approaches I can think of are to write a custom serializer or to serialize the value, both of which are worse.
> Set curlotsize when deserializing Ammunition

- ssw/src/main/java/ssw/gui/frmMain.java
- ssw/src/main/java/ssw/gui/frmMainWide.java
This fixes more issues related to saving quirks by correctly resetting them when the "New Mech" menu button is clicked.
> Reset quirks when clicking new mech button

- sswlib/src/main/java/components/PPCCapacitor.java
Changed the code to use the total BV from the rulebooks minus the weapon BV to be the actual BV of the capacitor.
> PPC Capacitor BV Update

- sswlib/src/main/java/Force/Force.java
- sswlib/src/main/java/Force/Unit.java
Will now split long Unit or Mechwarrior names into multiple lines.
> Updated Roster Printing Code

- BFB/src/main/java/BFB/GUI/dlgQuickAdd.java
- BFB/src/main/java/BFB/GUI/frmBase.java
- saw/src/main/java/saw/gui/dlgOpen.java
- ssw/src/main/java/ssw/gui/dlgOpen.java
- sswlib/build.gradle
- sswlib/src/main/java/list/UnitList.java
- sswlib/src/main/java/list/view/abView.java
- sswlib/src/main/java/list/view/tbBattleForceView.java
- sswlib/src/main/java/list/view/tbChatInformation.java
- sswlib/src/main/java/list/view/tbTotalWarfareCompact.java
- sswlib/src/main/java/list/view/tbTotalWarfareView.java
Attempt to fix Maelwys screen issues by instantiating the views once and just handing the list of units off when the view is selected.
> Select Unit screen update

- sswlib/src/main/java/list/abUnitData.java
This appears to be a regression of error https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/issues/143 in some form. I verified the fix works on Ubuntu 20.04, and don't expect it to break on any other OS'es due to this change.
> Fix protocol error on Linux when opening files

- saw/src/main/java/saw/gui/frmVee.java
- sswlib/src/main/java/components/CVArmor.java
- sswlib/src/main/java/components/CombatVehicle.java
- sswlib/src/main/java/visitors/VArmorSetVStealth.java
Updated the logic for Vehicle Stealth Armor to better match how Mech Stealth Armor is handled.  If you select Stealth Armor in SAW it will look for an existing ECM and add it if not already added.
> Improve SAW Stealth Armor handling.

- sswlib/src/main/java/components/Mech.java
Added check for Quad on the "arms" so that explosive items are correctly calculated when they are in the front legs.
> Update GetExplosiveWeaponPenalty for Quads

- sswlib/src/main/java/components/Gyro.java
Updated the Gyro code so that a "None" config will check for an Interface Cockpit and return a Standard gyro's DBV result.
#258
> Interface Cockpit wo Gyro

- sswlib/src/main/java/states/stArmorHD.java
- sswlib/src/main/java/states/stArmorISAB.java
- sswlib/src/main/java/states/stArmorISBR.java
- sswlib/src/main/java/states/stArmorISFF.java
- sswlib/src/main/java/states/stArmorISHF.java
- sswlib/src/main/java/states/stArmorISIR.java
- sswlib/src/main/java/states/stArmorISLF.java
TacOps states (page 92 of the new Split Version)
"IndustrialMechs that use any armor type other than Commercial, Industrial or Heavy Industrial (Standard) must be classified as Experimental-rules units. In addition, Experimental-rules IMs may also make use of all other BM-legal armor types."
#239
> Set Armor Level for IM to Experimental

- Data/Equipment/physicals.json
Fix issue #305 - *Medium Shield should not cause Jump speed to show as (0)*
Cause:
JSON reader for mech modifier sets bool to false by default.
Solution:
Add `CanJump` to Medium Shield attribute `Modifier`, with value of `true`.
> Fix #305 - Medium Shield disables jump

- .gitignore
- Data/Equipment/equipment.json
- Data/Equipment/quirks.json
- saw/src/main/java/saw/gui/dlgPrefs.form
- saw/src/main/java/saw/gui/dlgPrefs.java
- saw/src/main/java/saw/gui/frmVee.java
- saw/src/main/java/saw/gui/frmVeeWide.java
- ssw/src/main/java/ssw/gui/frmMain.java
- ssw/src/main/java/ssw/gui/frmMainWide.java
- sswlib/src/main/java/common/CommonTools.java
- sswlib/src/main/java/components/CVArmor.java
- sswlib/src/main/java/components/CVJumpJetFactory.java
- sswlib/src/main/java/components/Equipment.java
- sswlib/src/main/java/components/Mech.java
- sswlib/src/main/java/components/VehicularGrenadeLauncher.java
- sswlib/src/main/java/filehandlers/CVReader.java
- sswlib/src/main/java/filehandlers/CVTXTWriter.java
- sswlib/src/main/java/filehandlers/CVWriter.java
- sswlib/src/main/java/filehandlers/MechReader.java
- sswlib/src/main/java/filehandlers/MechWriter.java
- sswlib/src/main/java/filehandlers/TXTWriter.java
- sswlib/src/main/java/states/stChassisISCOBP.java
- sswlib/src/main/java/states/stChassisISCOQD.java
- sswlib/src/main/java/states/stChassisPBMBP.java
- sswlib/src/main/java/states/stChassisPBMQD.java
- sswlib/src/main/java/utilities/CVCostBVBreakdown.java
- sswlib/src/main/java/utilities/CostBVBreakdown.java
Several fixes and misc changes. There's two more PRs that will follow this, one that has fixes for mech and CV turrets and related UI, and the other for some MML compat options.
Improved error handling:
* Allow loading units with unknown equipment, also fixing an old backcompat check.
* Allow loading units with equipment in invalid locations.
* Unit saving no longer wipes file on error. Shows unexpected exceptions during saving in a dialog.
UI fixes:
* Fix regression from 69bbe7c9 that broke multiples of same equipment. I know there's another outstanding PR (#301) that's supposed to fix it, but don't think conflating an instance of an equipment and the "class" of that equipment for equality purposes is a good idea.
* Use equipment chooser panel from wide CV GUI in all other CV/mech GUIs. …
> Various fixes including for regressions on latest RC

- Data/Templates/Vee_HTML.html
- saw/src/main/java/saw/filehandlers/HTMLWriter.java
- saw/src/main/java/saw/gui/frmVee.form
- saw/src/main/java/saw/gui/frmVee.java
- saw/src/main/java/saw/gui/frmVeeWide.form
- saw/src/main/java/saw/gui/frmVeeWide.java
- ssw/src/main/java/ssw/gui/frmMain.java
- ssw/src/main/java/ssw/gui/frmMainWide.java
- ssw/src/main/java/ssw/gui/thHDTransferHandler.java
- ssw/src/main/java/ssw/gui/thLTTransferHandler.java
- ssw/src/main/java/ssw/gui/thRTTransferHandler.java
- sswlib/src/main/java/components/Ammunition.java
- sswlib/src/main/java/components/BipedLoadout.java
- sswlib/src/main/java/components/CVLoadout.java
- sswlib/src/main/java/components/CombatVehicle.java
- sswlib/src/main/java/components/Equipment.java
- sswlib/src/main/java/components/LiftHoist.java
- sswlib/src/main/java/components/MGArray.java
- sswlib/src/main/java/components/MechTurret.java
- sswlib/src/main/java/components/QuadLoadout.java
- sswlib/src/main/java/components/RangedWeapon.java
- sswlib/src/main/java/components/SponsonTurret.java
- sswlib/src/main/java/components/TripodLoadout.java
- sswlib/src/main/java/components/Turret.java
- sswlib/src/main/java/components/abPlaceable.java
- sswlib/src/main/java/components/ifCVLoadout.java
- sswlib/src/main/java/components/ifTurret.java
- sswlib/src/main/java/filehandlers/CVReader.java
- sswlib/src/main/java/filehandlers/CVWriter.java
- sswlib/src/main/java/filehandlers/MechReader.java
Mech turrets:
* Fix quad mechs to allow both torso and head turrets (they're considered different types of mech turrets).
* Revamp mech turret code to fix edge cases and allow equipment.
* Align mech turret/rear-mounting code, both in lib and GUI logic.
* Drag&drop weapon/equipment retains mech turreted status.
* Displaced weapon/equipment (when dragging another equipment onto it, requiring reallocation) also retains mech turreted status.
* Disallow mounting ammo in mech turret. (Technically, I think ammo can be allocated to the turret but shouldn't count for turret tonnage, which functionally should be the same as disallowing turreted ammo.)
Vehicle turrets:
* Add rear turret tonnage to info bar. To help make it fit in the info bar, turret tonnages are hidden if corresponding turret …
> Mech/vehicle/omnivehicle turret fixes & improvements

- Data/Equipment/physicals.json
Updated the Medium Shield JSON to include ConfigOnly field for the Modifiers. This should probably be done with all the equipment to allow them to behave correctly for Omni Mechs.
> Bug Fix: Medium Shield on an omni mech modifies the reported speed for every variant. #322
